### ISSUE TITLE
Customization is totally missing

### ISSUE THREAD

**Issue by yogwoggf** [gelly-gmod/gelly#109]
## Context

Currently, people have no *easy* way to customize *anything* about Gelly.
There are several reasons for that:
- No configuration infrastructure
    - As in, we really just have tons of sources of truth for configuration which are scattered all over the code base
        - Fluid simulation module (`IFluidSimulation`)
        - Fluid renderer module (`SplattingRenderer::Settings`)
        - Composite module (`PipelineConfig`)
        - Lua module (`GELLY_SIM_TIMESCALE`, `GELLY_ENABLE_SIM`) 
- Level of abstraction has not yet been decided
    - i.e: should the graphics be organized like Roblox/Fortnite with "qualities" or like GW2 with specific options and sliders for every internal setting
    - i.e: should we create a set of fluid parameters like: smoothness, stickiness, thickness? or should we expose direct access to FleX parameters like fluid rest distance, viscosity, cohesion, adhesion, etc.
- There is no UX design for configuration
    - There's no UX design of any kind for a sort of central control panel, like GWater2.
    - Ideation and brainstorming has to be done first
    - This is decoupled from the above settings

## Scope

- Create a central facade for use in `gelly-gmod` which controls all necessary non-ephemeral settings
    - Should allow access to a central setting structure
    - Said structure should have get/set functions (will be serialized by the addon)
- Create a UI for managing the new settings

## Acceptance Criteria

- Gelly can be customized from a UI
- Gelly settings are saved

**Comment by yogwoggf** [comment]
Scope and acceptance criteria are *wide,* may want to split these off into subtasks

**Comment by cast-e** [comment]
> i.e: should the graphics be organized like Roblox/Fortnite with "qualities" or like GW2 with specific options and sliders for every internal setting

I think this could be both, like quality "presets", but that you can still change manually, unlike GW2 that only has manual options

**Comment by yogwoggf** [comment]
# Update
The customization update is nearly done. More work is required to fully realize preset creation, but besides that the menu, settings infrastructure and console variable design is complete.
