### ISSUE TITLE
Limit the rest distance ratio convar

### ISSUE THREAD

**Issue by yogwoggf** [gelly-gmod/gelly#142]
## Context

Players are messing with the slider and are consistently reporting <0.5 values cause the simulation to blow up.

## Scope

- Limit the slider range to [0.5, 1].

## Acceptance Criteria

- Users cannot select a rest distance ratio below 0.5.

**Comment by cast-e** [comment]
Don't limit it to 0.5 to 1 because both too low values and too high values make flex lag.
You should probably limit it from 0.5 to 0.8 or 0.7
