### ISSUE TITLE
[BUG]: The fluid doesn't collide with some props even tho gwater does

### ISSUE THREAD

**Issue by SolsticeSpectrum** [gelly-gmod/gelly#43]
### GPU

GTX 1060

### Operating System

Windows 10

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

Here is the map used for testing fluids: https://steamcommunity.com/sharedfiles/filedetails/?id=3253756129&searchtext=gwater

**Example 1:** 
On this map, there are containers for fluids with door on the bottom so you can release it somewhere
Gwater collides correctly with these boxes but gelly doesn't
![image](https://github.com/yogwoggf/gelly/assets/38611351/4057a2d4-8e79-451c-8b8b-9146695b1c7d)

**Example 2:**
On the same map, gelly flows through all doors
![image](https://github.com/yogwoggf/gelly/assets/38611351/faf49520-32f7-4b77-83ee-3bd233141fb9)

**Comment by SolsticeSpectrum** [comment]
As comparison, here is gwater:
![image](https://github.com/yogwoggf/gelly/assets/38611351/d3197c0a-8504-4c2d-aefb-80c11d49a318)

**Comment by yogwoggf** [comment]
Triaged in #47

**Comment by Derpius** [comment]
Closed incorrectly - Doors are regular entities not static props

**Comment by SolsticeSpectrum** [comment]
@yogwoggf Use the test map I linked pls

**Comment by cast-e** [comment]
@yogwoggf shouldn't this be closed by #102?

**Comment by yogwoggf** [comment]
Yep
