### ISSUE TITLE
[BUG]: Foam particles move too fast before settling causing flickers

### ISSUE THREAD

**Issue by SolsticeSpectrum** [gelly-gmod/gelly#44]
### GPU

GTX 1060

### Operating System

Windows 10

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

The foam particles move so fast, they cause flickers in the fluid, they are okay when they get stable after finishing pouring
![image](https://github.com/yogwoggf/gelly/assets/38611351/a1fc0c16-a987-451c-864b-47e9348a9e2e)

**Comment by yogwoggf** [comment]
Ultimately as it stands FleX's diffuse particles are incompatible with our sped up timestepping scheme and we can't really control this sort of flickering behavior.

Perhaps #53 can fix this issue later on, but overall it isn't necessarily high priority

**Comment by yogwoggf** [comment]
This was removed a while ago, closing.
