### ISSUE TITLE
[BUG]: The pixel shader causes huge FPS drops

### ISSUE THREAD

**Issue by SolsticeSpectrum** [gelly-gmod/gelly#45]
### GPU

GTX 1060

### Operating System

Windows 10

### Is this specific to performance?

- [X] Yes
- [ ] No

### Issue Type

Low FPS

### Incident Description

If the fluid is stationary, it's about 30 FPS, but if it moves around, for example by pouring it out of a cylinder, my FPS drops down to 3 if I'm very close to it before it settles back on 30. Since it mostly happens when I'm close it, it's most likely caused by the pixel shader.

**Comment by SolsticeSpectrum** [comment]
Somehow this is now even worse

**Comment by yogwoggf** [comment]
This is difficult to triage as GPU related software heavily benefits from an analytical take on optimization. It's tough to optimize for everyone's hardware--but there are planned features to remedy this issue, according to some recent timing analysis.

1. Lower filter size to reduce mega texture lookups--should provide a benefit to your issue
2. Menu to change rendering settings, particularly to reduce the quality of the rendering
3. Downscaling the entire renderer and upscaling at the cost of blurriness. This'll be a separate ticket for sure as it's a more open-ended solution, but probably will help the most.

**Comment by yogwoggf** [comment]
Still a bit of an issue, but heavily resolved since #94
