### ISSUE TITLE
[TICKET]: Fix blood mod damage type logic

### ISSUE THREAD

**Issue by Derpius** [gelly-gmod/gelly#59]
### Context

- The blood mod selects different settings for spawning particles based on the damage type that was received
- It currently does this via a lookup table where each key is a value of the `DMG` enum (with some being combinations of various flags)
- This is not valid, as the `DMG` enum is used as a bitflag - i.e. a LUT key of `DMG_BULLET` will _only_ match on a damage event with that single field set, and nothing else
- This causes various damage events to not trigger particles to be spawned

### Scope

- Change the blood mod configs into an array of objects containing the existing properties, plus the following new one
  - `damageFlags` - Same as the current key (this should be both single enum values and `bit.bor`'d combinations of flags
    - This should **NOT** be used to identify specific SWEPs as the current code does - that is not a robust way to tell, you should get the inflictor/weapon instead
  - The order of the tables in this array will define the priority order that we check them in
- Iterate over the table with `ipairs` and `bit.band` the damage's type with the `damageFlags` property
- Spawn particles on the first match and exit the loop

### Acceptance Criteria

- Weapons dealing damage with multiple flags set still match to presets which require only one of those flags to match
- Presets are evaluated in the order they're defined, with the first preset where `bit.band(damageType, preset.damageFlags) ~= 0` is `true` getting used
- **Could:** Presets are defined as config-only Lua or JSON in the `/data` directory (facilitating future work to share or edit them in-game)

### Other

We should consider whether damage types are the way to go here from a product perspective

I think they should be a fallback, with the primary configuration method using the name of the weapon as the key in a lookup table - Both a small pistol and HMG may deal `DMG_BULLET`, but we probably want different configs for each

**Comment by yogwoggf** [comment]
For bookkeeping, #59 could be a solution for this ticket, but it needs extensive code review

**Comment by Derpius** [comment]
59 is this issue’s ref, you mean #69 

Also you should be able to edit other people’s pr descs to include closing tags like “Resolves”
