### ISSUE TITLE
Add install script to releases and remove .gitkeep from prod

### ISSUE THREAD

**Issue by SolsticeSpectrum** [gelly-gmod/gelly#77]
## Context

Currently the way to install gelly is to manually extract the zip into Garry's Mod folder but removing it is a bit of a pain

## Scope

This provides an easy to use installer with uninstall option in place

## Acceptance Criteria

Ideally it should put this into release next to the zip
Also maybe stop including `.gitkeep` files, they aren't a big issue but there is no reason to have them there

## Other

Here is the install script:
[gelly_install.txt](https://github.com/user-attachments/files/15803459/gelly_install.txt)

**Comment by yogwoggf** [comment]
I don't think a script is the best way to go about this, and so far nothing appears to be wrong with .gitkeep. Also, this is a fairly aged issue in need of a refresh to account for Gelly's new installation.
