### ISSUE TITLE
error crash

### ISSUE THREAD

**Issue by oriolprogamer712** [gelly-gmod/gelly#97]
[gelly-log-2024-07-02.log](https://github.com/user-attachments/files/16071330/gelly-log-2024-07-02.log)

**Comment by yogwoggf** [comment]
This is in the wrong place, please follow the "Bug Report" link, which is our Discord.
---

Either way, unfortunately I can't decipher what went wrong. It might be worth uploading the respective crash dump in the `crashes ` folder.

![image](https://github.com/gelly-gmod/gelly/assets/100450992/2e344bb9-c237-441e-a9d2-610352ead484)
